apiVersion: batch/v1
kind: Job
metadata:
  name: almoghershko-50epochs-train-denoise-rajah
spec:
  backoffLimit: 0
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-2080-Ti
                - NVIDIA-GeForce-RTX-3090
                - Tesla-V100-SXM2-32GB
      containers:
      - name: container
        image: almogh/tf-almog
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: "16Gi"
            nvidia.com/gpu:  "1"
          limits:
            cpu: "2"
            memory: "16Gi"
            nvidia.com/gpu:  "1"
        command: ["/bin/bash", "-c"]
        args:
          - cd root; 
            git clone https://github.com/almoghershko/thesis.git;
            dt=$(date '+%Y_%m_%d__%H_%M_%S');
            run_name="$dt"__"$RUN_PREFIX";
            pip install -r thesis/requirements.txt;
            python thesis/scripts/run_train_100K_V4_raja.py $run_name 1 50 5 6 40 &> stdout.txt;
            aws --endpoint https://s3-west.nrp-nautilus.io s3 cp ./stdout.txt s3://tau-astro/almogh/workdir3/runs/$run_name/;
        env:
          - name: "RUN_PREFIX"
            value: "50EpochsTrainDenoiseV4Raja"
      restartPolicy: Never
